server:
  port: 8080

spring:
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: none

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/test?createDatabaseIfNotExist&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: fatou
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5